version: '3'

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:14-alpine3.17
    env_file:
      - ".env"
    ports:
      - "50421:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

#    environment:
#      - "POSTGRES_DB=${PG_DATABASE_NAME}"
#      - "POSTGRES_USER=${PG_USER}"
#      - "POSTGRES_PASSWORD=${PG_PASSWORD}"